#  - type: file
#    path: svgs/example.svg
#    format: svg
#    outputs:
#      - format: png
#        directory-override: general
#        sizes: [ 512 ]
#        color: '#ffffff'
#        background: '#000000'
#        margin: '18%'
source-defaults:
  recurse: false
output-defaults:
  format: png
  sizes: [ 512 ]
  color: '#ffffff'
  background: '#000000'
  margin: '18%'
sources:
  # png
  - type: folder
    path: png
    format: png
    outputs:
      # general
      - directory-override: general
      # groups
      - directory-override: group
        background: '#58595b'
        selectors:
          - exchange
          - vmware
      # groups - overrides for specific icons due to their size
      - directory-override: group
        sizes: [ 128 ]
        background: '#58595b'
        selectors:
          - ekm-insight
      - directory-override: group
        sizes: [ 256 ]
        background: '#58595b'
        selectors:
          - datto-rmm
      # production apps
      - directory-override: production
        background: '#A32035'
        selectors:
          - cisco
          - duo
          - it-glue
  # svg
  - type: folder
    path: svg
    format: svg
    outputs:
      # general
      - directory-override: general
      # group
      - directory-override: group
        background: '#58595b'
        selectors:
          - exchange
          - malwarebytes
  # download - fontawesome
  - type: url
    path: 'https://use.fontawesome.com/releases/v6.2.1/fontawesome-free-6.2.1-web.zip'
    format: svg
    target-folders:
      - svgs/brands
      - svgs/solid
    outputs:
      # general
      - directory-override: general
        selectors:
          - apple
          - broom
          - calendar-days
          - certificate
          - circle-exclamation
          - circle-xmark
          - clock
          - cloud
          - cloud-arrow-up
          - cloudflare
          - comments
          - computer
          - database
          - diagram-project
          - download
          - dumpster-fire
          - ellipsis
          - eye
          - file-signature
          - film
          - gauge-high
          - gitlab
          - globe
          - image
          - key
          - layer-group
          - list
          - list-check
          - list-ol
          - lock
          - mobile
          - paper-plane
          - plane-departure
          - rotate
          - scroll
          - server
          - terminal
          - unlock
          - user
          - user-gear
          - user-group
          - user-minus
          - user-slash
          - user-xmark
          - users
          - users-gear
          - users-slash
      # groups
      - directory-override: group
        background: '#58595b'
        selectors:
          - circle-play
          - comments
          - copy
          - cubes
          - database
          - ellipsis
          - file-invoice-dollar
          - house-laptop
          - microsoft
          - network-wired
          - plug
          - python
          - scroll
          - users-gear
          - windows
      # production apps
      - directory-override: production
        sizes: [ 16, 24, 32, 48, 64, 96, 128, 256, 512 ]
        background: '#A32035'
        selectors:
          - circle-exclamation
          - gauge-high
          - globe
          - list-check
